<?php
	ini_set("session.save_path", "/home/unn_w13020720/sessionData");
	session_start(); 
	include 'data_conn.php';
	require_once('functions.php');
	
	echo htmlSet();
	//Check to see if user is logged in.
	if(isset($_SESSION['signed_in']) && $_SESSION['signed_in'] == true){
		echo navLogOut("{$_SESSION['username']}");
	}
	else{
		echo navLogIn();
	}
			echo pageStart("cdContSearch");

			include 'data_conn.php';
		
			//Set Variables for Search Box. If no entry is returned, set variable to null.
			$sTitle = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'title') ? trim($_GET['title']):null);
			$sYear = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'year') ? trim($_GET['year']):null);
			$sCat = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'category') ? trim($_GET['category']):null);
			$sPub = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'publisher') ? trim($_GET['publisher']):null);
			$sPrice = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'price') ? trim($_GET['price']):null);
			$sKeywords = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'keyword') ? trim($_GET['keyword']):null);
			$sSort = mysqli_real_escape_string($conn, filter_has_var(INPUT_GET, 'order') ? trim($_GET['order']):null);
		
			//Filter out any quotes or encoding tags
			$sTitle=filter_var($sTitle, FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
			$sKeywords=filter_var($sKeywords, FILTER_SANITIZE_STRING, FILTER_FLAG_NO_ENCODE_QUOTES);
			//Send an error message for the string length if it exceeds the longest possible characters
			if(strlen($sTitle)>65){
				die("<p>Your Title request exceeds the word limit. Try narrowing your search!</p>");
			}
		
			//SQL return for empty search bars. Standard return on submit.
			$sql = "SELECT CDID, CDTitle, CDYear, catDesc, pubName, CDPrice 
					FROM nmc_cd
					INNER JOIN nmc_publisher ON nmc_publisher.pubID = nmc_cd.pubID
					INNER JOIN nmc_category ON nmc_category.catID = nmc_cd.catID
					WHERE 1";
		
			//Create empty variable to add to the original sql statement
			$search = "";
		
			//if variable is not empty, add a string of sql to the empty variable
			if (!empty($sTitle)) {
		   		$search .= " AND CDTitle LIKE '%$sTitle%'";
			}
			if (!empty($sYear)) {
		   		$search .= " AND CDYear = '$sYear'";
			}
			if (!empty($sCat)) {
		   		$search .= " AND catDesc = '$sCat'";
			}	
			if (!empty($sPub)) {
		   		$search .= " AND pubName = '$sPub'";
			}
			if (!empty($sPrice)) {
				$search .= " AND CDPrice BETWEEN '$sPrice'-0.99 AND '$sPrice'";
			}
			if (!empty($sKeywords)) {
		   		$search .= " AND CDTitle LIKE '%$sKeywords%'";
			}
			if($sSort=='year'){
				$search .= " ORDER BY CDYear DESC";
			}elseif($sSort=='phl'){
				$search .= " ORDER BY CDPrice DESC";
			}elseif($sSort=='plh'){
				$search .= " ORDER BY CDPrice ASC";
			}elseif(empty($sSort)){
				$search .= " ORDER BY CDTitle";
			}
			//redefine the sql command, with the original plus the new string generated by the search form
			$newSQL = $sql.$search;

			//process the sql command
			$rsSearch = mysqli_query($conn, $newSQL) or die (mysqli_error($conn));
		
			//die error message if there are no returns
		
			$rowCnt = mysqli_num_rows($rsSearch);
			if($rowCnt ==0){
				echo "<p>I'm sorry, no results were found based on your criteria. 
					Try adjusting your search terms!</p>\n";
				die("<p><a href=\"products.php\">Back...</a>\n</p>");
			} else{
				echo "<p class=\"resultNum\">Showing $rowCnt results...</p>";
			}
		
			//organize the sql returns as rows for display for each result
				while ($row = mysqli_fetch_assoc($rsSearch)){
		
					$CDID = $row['CDID'];
					$title = $row['CDTitle'];
					$year = $row['CDYear'];
					$pub = $row['pubName'];
					$cat = $row['catDesc'];
					$price = $row['CDPrice'];

					//convert special characters 
					$rCat = htmlspecialchars($cat);
		
						echo "<div class= \"CD\">\n";
								echo "<div class=\"cdimage\">\n";
									echo "<a href=\"products.php?CDID=$CDID\">&#9835;</a>\n";
								echo "</div>\n";
								echo "<div class=\"cdbreak\"></div>\n";
		
								echo "<div class=\"Title\">
									<span class= \"title\">
									<a href=\"products.php?CDID=$CDID\">$title</a>
									</span>
									</div>\n";
		
								echo "<div class=\"container\">\n";
									echo "<div class=\"content\"><h2>Year</h2><span class= \"year\">$year</span></div>\n";
									echo "<div class=\"content\"><h2>Genre</h2><span class= \"cat\">$rCat</span></div>\n";
									echo "<div class=\"content\"><h2>Price</h2><span class= \"price\">&pound;$price</span></div>\n";
								echo "</div>\n";
							echo "</div>\n";
				}
		
			//close the connection
			mysqli_free_result($rsSearch);
			mysqli_close($conn);

			echo pageEnd();
	echo htmlEnd();
?>